### ISSUE TITLE
Compare Other LLM?

### ISSUE THREAD

**Issue by yuanjunchai** [open-compass/GAOKAO-Eval#1]
Nice work!

So do you plan to compare other work like Llama3, GLM4, Baichuan, Phi-3 etc?

**Comment by yhcc** [comment]
We primarily test the recently released models (and their corresponding multimodal models). Since the evaluation requires scoring by experienced graders, this assessment cannot easily scale to a large number of models. At this stage, there are no plans to expand the range of models.

**Comment by yuanjunchai** [comment]
I am willing to make some contribution to this program if available. Such as helping you to run more tests.

**Comment by yhcc** [comment]
Thank you for offering to help. We are currently busy testing more college entrance exam papers from various provinces and cities. Once these scores are released, we may proceed with our next steps. If we need assistance at that time, we will reach out to you.
